/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: eDF77JsGistQwyReSVJoYU

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_9NbJw1WiSNpx } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 9NbJW1WiSNpx/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_9NbJw1WiSNpx
});
